# Day One

| Command | Function |
|  ------	| ------	| 
|Command-N (or Command-1)	|New Entry|
|Command-2	| Timeline View|
|Command-3	| Calendar View|
|Command-4	| Reminders (Mac OS X 10.8 and earlier) or Map View (Mac OS X 10.9)|
|Command-5	| Reminders (Mac OS X 10.9)|
|Control-Shift-D	| Menu Bar Entry (customizable in Preferences)|
|Left/Right Arrows	| Previous/Next Day|
|Up/Down Arrows	| Previous/Next Item in a List|
|Command-E (or Command-Enter)	| Toggle Entry Edit Mode|
|Command-F	| Open Search Popover Menu|
|Command-T	| Open Tag Menu|
|Spacebar/Shift-Spacebar	|Page Down/Page Up|
|Command-Comma	|Preferences|
|Command-Shift-L	|Lock Journal|
|Command-Shift-E	|Export|
|Command-Control-F	|Enter Full Screen|
|ESC	|Exit Full Screen View and Menus|  

from [DayOne](https://dayone.zendesk.com/hc/en-us/articles/200145895-Keyboard-shortcuts)